"""positions exit signals earn recommendations

Revision ID: 2c7bc58b75f7
Revises: 5ea65cbf51f8
Create Date: 2026-09-02 01:59:01.637761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '2c7bc58b75f7'
down_revision: Union[str, None] = '5ea65cbf51f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earn_recommendations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('idle_capital_usdt', sa.Float(), nullable=False),
    sa.Column('trading_reserve_usdt', sa.Float(), nullable=False),
    sa.Column('emergency_reserve_usdt', sa.Float(), nullable=False),
    sa.Column('recommended_earn_usdt', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trade_plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy', postgresql.ENUM('gainer_hunter', 'recovery_hunter', 'hot_market_margin', 'capital_optimizer', name='strategytype', create_type=False), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('remaining_fraction', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('profit_targets_pct', sa.JSON(), nullable=False),
    sa.Column('targets_hit', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('open', 'partially_exited', 'closed', name='positionstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_price', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('peak_price_since_entry', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_plan_id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('exit_signals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sell_fraction', sa.Float(), nullable=False),
    sa.Column('price_at_trigger', sa.Float(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exit_signals')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('earn_recommendations')
    # ### end Alembic commands ###
