"""initial schema

Revision ID: 5ea65cbf51f8
Revises: 
Create Date: 2026-09-01 18:47:25.086723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ea65cbf51f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('strategy', sa.Enum('gainer_hunter', 'recovery_hunter', 'hot_market_margin', 'capital_optimizer', name='strategytype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('candidates_analyzed', sa.Integer(), nullable=False),
    sa.Column('proposals_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('risk_result', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('market_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('market_regime', sa.String(), nullable=True),
    sa.Column('gainers_scanned', sa.Integer(), nullable=False),
    sa.Column('losers_scanned', sa.Integer(), nullable=False),
    sa.Column('hot_candidates_found', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sessions_session_date'), 'market_sessions', ['session_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trading_mode', sa.Enum('read_only', 'approval_required', 'autonomous', name='tradingmode'), nullable=False),
    sa.Column('emergency_halted', sa.Boolean(), nullable=False),
    sa.Column('halted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('market_candidates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy', sa.Enum('gainer_hunter', 'recovery_hunter', 'hot_market_margin', 'capital_optimizer', name='strategytype'), nullable=False),
    sa.Column('status', sa.Enum('analyzing', 'watching', 'qualified', 'rejected', 'trade_proposed', 'executed', name='candidatestatus'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('daily_change_pct', sa.Float(), nullable=False),
    sa.Column('quote_volume_24h', sa.Float(), nullable=False),
    sa.Column('spread_bps', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_source_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['market_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_candidates_symbol'), 'market_candidates', ['symbol'], unique=False)
    op.create_table('risk_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('max_spot_trade_usdt', sa.Float(), nullable=False),
    sa.Column('max_spot_allocation_pct', sa.Float(), nullable=False),
    sa.Column('max_margin_trade_usdt', sa.Float(), nullable=False),
    sa.Column('max_margin_allocation_pct', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_slippage_bps', sa.Float(), nullable=False),
    sa.Column('min_opportunity_score', sa.Float(), nullable=False),
    sa.Column('min_recovery_score', sa.Float(), nullable=False),
    sa.Column('hot_score_threshold', sa.Float(), nullable=False),
    sa.Column('gainer_hard_stop_pct', sa.Float(), nullable=False),
    sa.Column('recovery_hard_stop_pct', sa.Float(), nullable=False),
    sa.Column('recovery_take_profit_pct', sa.Float(), nullable=False),
    sa.Column('trading_reserve_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trade_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('candidate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy', sa.Enum('gainer_hunter', 'recovery_hunter', 'hot_market_margin', 'capital_optimizer', name='strategytype'), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('position_size_usdt', sa.Float(), nullable=False),
    sa.Column('estimated_slippage_bps', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('profit_targets_pct', sa.JSON(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('market_conditions', sa.JSON(), nullable=False),
    sa.Column('risk_check_passed', sa.Boolean(), nullable=False),
    sa.Column('risk_check_notes', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'submitting', 'open', 'partially_exited', 'closing', 'closed', 'failed', 'cancelled', 'risk_rejected', name='tradeplanstatus'), nullable=False),
    sa.Column('binance_order_id', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['market_candidates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_plans_idempotency_key'), 'trade_plans', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_plans_idempotency_key'), table_name='trade_plans')
    op.drop_table('trade_plans')
    op.drop_table('risk_policies')
    op.drop_index(op.f('ix_market_candidates_symbol'), table_name='market_candidates')
    op.drop_table('market_candidates')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_sessions_session_date'), table_name='market_sessions')
    op.drop_table('market_sessions')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
